class QuitError(Exception):
    pass

class RestartError(Exception):
    pass